version: '3'

services:
  mysql1:
    image: mysql:8.0.27
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1

    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    networks:
      - mycat-network

  mysql2:
    image: mysql:8.0.27
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1

    ports:
      - 13307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    networks:
      - mycat-network

  mycat1:
    image: "registry.cn-guangzhou.aliyuncs.com/uuzzzga/mycat:master"
    restart: always
    ports:
      - 8066:8066
    links:
      - mysql-prototype
    depends_on:
      - mysql-prototype
    volumes:
      - ./mycat/conf/:/usr/local/mycat/conf
      - ./mycat/logs/:/usr/local/mycat/logs
    networks:
      - mycat-network

  mysql-prototype:
    image: mysql:8.0.27
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1

    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mycat
      TZ: Asia/Shanghai
    networks:
      - mycat-network

networks:
  mycat-network:
    driver: bridge
